language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
- gradle build
- gradle createExe
- gradle versionTxt
- gradle createZipLivrable


deploy:
  provider: bintray
  file: "descriptor.json"
  skip_cleanup: true
  user:
    secure: "MmSD7mMV2/TlkW7Y4qYErl5oUv2gxBT1Kh6nkMI6oViZZ0f/OZWHoAimSKyjReWlB8g1l3ZKcmsq1D6fDVon2atmGnOQCBMmRnOIK6Kq88b5XvRU6Tux+gGxxXOFhVSUvgAwtmTQXX1p1HEhER1WiMbc1E2GxJn9VnNi5x/HvWp163B4KZqwsO4LBT2Kxkf1UPuMWFDtPVtexCJ/4cJ7O0XtZhAAOEpEpIVUL1gug1T+YubSE6C52/IvFelNW0NKnmBVNHxREPGw06r51qW2pdVePm13MKLa3Qkg6T5QCS61IUsXj7MKCIlEDd+/sq6iOI445ZD9Zv0PVAIAwYluoZrSmc1PJVdcsjr/9EzZS9+weLmaIdGgiIFAGP6h9R/rfKuLEEqjo2CotxiKSEnx7YTYwcoI8d/5Idy5EjO5yC+p+77wtIi8z69OmpSgx5Sj6U8zzVJLnWtemKxravtu+qD3x7udWh7hsyuouyofIrpha0av/cNonmfVxl14Mzr4PtPC9tZ1ibfAHjKdYfujREfgMHreKhMo2ntL7LifJP3T+Fj/d0Tge5aflHzkC3gJYLZiggl5OYdF3VcpNIAt4a9Rfd2xJfNk5SFqkYSQIovn079C0/hptQlFqgL406s+dz7W4z8En5QgJmuB//2D9sJOfhlUxyZO1/hTclk1nl0="
  key: 
    secure: "Ml6m0FhJTxa9kDEAcJ33OBgRT3MQb2lZJRC8JXpoO7BwwFZB3obnONk85u20IY5NMSBXwU4RNk73bQEk2LFTkFsjuwZkUTslHawNpd4m+HaB0PG4/GXLRQns1U7dpbctPodNKRin+vgas4Bld/vUNldqMaTZs/qv0iJBB7spGwCkMecTc3643hk232M51gKvBFMJCGAFFtfpy8iYe+gHCVduqHND6lgIB+408keQW5pb3ECg9Vq5Sg9+0eNE1WzL9hkW4mQuVU6oyf9DfLNMPcxqUeLuTz1XFeAEro/BQZZEwK3mn7OOCWQ9zTYB5Rhayn0lG/F4dNLEyLgj/xBnS4H3r0M2PxtOZ2g+B0ShsLQr6uf9+OYOVGLMasqvjo/Dt4/fPSh5OssPgHRZ9+2ZhhXj/m122KiahSiT2kFUVKNtR0lstA2W6w+20atuyigeeUenN/w7yPPi5o8+bAWFHwelWOQj4RKaWmEBdpvPvLDzseDwjZydGqvAagLVLgp/rC5g5RW7HqcSPkPTtXfKmLLjFGLFy8tB1CDKkqUPFuUsdsTpcNBNVfNQyYEcVdT1ag8huqvkn7SI0Ezh2QGwraC1S/z2+6O5jMfX/IvgZhfyCi/CYaZA5z3WOQcFXyYbDQTNb59vGM9BdYGYoT09lSNvXhXO5ywg0/72hl31loY="
  on:
    tags: true