language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
- gradle build


deploy:
  provider: bintray
  file: "descriptor.json"
  user:
    secure: "ZGmkGYF4PPDhNYVeZ5jJHn7wwIIn5aXN8bl66eiGyfI1015vYUn5Wa4S+dm2mxlv/tIxm4hD+3+7O1NXQVaEOT6Ws7JdkIWSAOTT1VtQEj4xcRsrdeZYmKJx/uB441lH3ZvRfT78/U+S9ogLuP/Q+9Mz1lLGSBisDMI0y6a4vcTnu6Yw86MbEgRLW+JI1HOXizHXEjda2YqH1DKML09QD/SsKX9Sj47g5DanFlAGVed1a8FEReypNRKi4UbjVSqjEKQKBqqDBpMLzx0sNQs8cRjsecdoL3/Xyzw8j3bnoZa90ngfqlie0OBluzyfqtRKBhZSU8ojvuQT7aYPs+bp/5yC+SGES5kw94m3qLrWXqgW7U1KcO3dVqcSf3Le9b+IPLkWwjfCZSUrKmZzFWC6b7rWBbpcXn8OcxRnBZwGc8N58SuhnOfeon8nlewX280KtpFGbhzR4a+58SOwCid1g/vJd8OkHo+VqGglNrycJQ5u0A3FvTmeAD+0iPXl1F2scMtFE66sWSsd0MEXBRgUi3DKMHPnQzR7aSEspUWB8Ub/cYEM5RrHschsn4ybP5LFGQiGeL3JDco2JR5Qa87PyCmVq8h6XPh+3AkoSBcTnaqSfKXYNyUOyuioyYTHXS06YHLd4YTXDnbVCCmKnwYZSn6nso10HROWfQ5VNxiui54="
  key: 
    secure: "mWuFywac0BbgMUZvyjiytWy54ZMrQfIJGKo1m5y6NV4J9paSfc0xyDxdRVluAGMCyTwm8uJLvMe+OiOKBBLJiQkfI3RVSbyJ8fr2sobK+3kmbZJuPUOEMafTdPHjMuhw9UCKilOCaa0uqrvy9NEmvSWKQAY217DMwlYTCB2pXj38mOywe/fPryVRrnmZ2WgsLTXVL8tbpsvQamY6+ahnf0fyubRJQvEeyhvqt6/i18W68xzgKwWR7BxQ7xEMhZqG3TT/RhlJdNGy/12SDz1q4yw/X7pwkwjwjKgrK5AAEOtgBdKUvC8OwOMmxamw3MK+pv+ycEvNfQ6l77SgHqq6THRIwhEV4uiqlfLYVoDMRrW3ciQ4WV1bqa98ZU4Pz3jZSGz3uRoZLegEXKC3liOAfQovslKyG3xRzxZFRCVHkAeUl/7+19mDm3TtZ7uuAETRudJwNit+AkEfTXyptb8N2HNiwlTYZRh2oO9MlkFB1pAhyDv7Voc8g/uYF7iuA9RiCYvFDaTVwqbV22hNrPfiANRId1tfhAoWwSS7FGXiQbtrs1eeWzKu5pT+/1uyCMnQpwHFfF8nYL933fiUsTkwQQnKK36t5TEhopyB6YNBqKEY4FIqiCB12TMhqaG6QkImceSPuXg1+d9TZ4fL6zfxMChmviXV9R4U4JNO0XBDmXs="
  on:
    all_branches: true